spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    url: jdbc:mysql://8.134.218.243:53306/dragon_dev?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: guddqsZ.0
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9797